name: Deploy to CloudPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to CloudPanel
        run: |
          scp -r * beautys@62.72.57.63:/home/beauty/htdocs/book-beauty.abym.co.in

      - name: Restart PM2
        run: |
          ssh beautys@62.72.57.63 "cd /home/beauty/htdocs/book-beauty.abym.co.in && pm2 restart all"
